site_name: Mobile Robots Oficial Site

repo_name: Mobile-Robots-Group-UC3M/MobileRobotsDocumentation
repo_url: https://github.com/Mobile-Robots-Group-UC3M/MobileRobotsDocumentation
edit_uri: blob/master/docs/

theme:
  name: material
  language: en
  logo: fig/roboticslab.svg
  favicon: fig/favicon.ico
  features:
    - content.action.edit
    - content.action.view
    - content.code.copy
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.suggest
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light-blue
      accent: light-blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light-blue
      accent: light-blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

extra:
  social:
    - icon: material/web
      link: http://roboticslab.uc3m.es/
    - icon: fontawesome/brands/github
      link: https://github.com/Mobile-Robots-Group-UC3M
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/mobile-robots-uc3m/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@MobileRobotsUC3M

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML


exclude_docs: |
  fig/README.md
  fig/editable/README.md

nav:
- Home: README.md
- About Us: about/about.md
- ADAM:
  - ADAM/README.md
  - ADAM v1.0: ADAM/ADAM_v1.0.md
  - ADAM v2.0: ADAM/ADAM_v2.0.md
- Navigation: Navigation/demo.md
- Vision: Vision/demo.md
- Manipulation: 
  - Manipulation/demo.md
  - Data Acquisition: Manipulation/datacq.md
- Grasping: Grasping/demo.md
- Simulation: 
  - Indoor Environments: Simulation/Indoor.md
  - ADAM Simulator: Simulation/ADAMSim.md
- Hardware: Hardware/demo.md

use_directory_urls: false

markdown_extensions:
  - attr_list # for mkdocs-pdf
  - mdx_math
  - toc:
      permalink: '#'
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search
  - open-in-new-tab
  - git-revision-date-localized
  - table-reader
  - include-markdown
  - mermaid2
  - mkdocs-pdf
  - autorefs
